export class AsientoDiario {
    constructor(
       public asiento: string,
       public paquete: string,
       public  tipO_ASIENTO: string,
       public fecha: Date,
       public contabilidad: string,
       public origen: string,
       public  clasE_ASIENTO: string,
       public  totaL_DEBITO_LOC: number,
       public  totaL_DEBITO_DOL: number,
       public  totaL_CREDITO_LOC: number,
       public  totaL_CREDITO_DOL: number,
       public ultimO_USUARIO: string,
       public  fechA_ULT_MODIF: Date,
       public marcado: string,
       public  notas: string,
       public  totaL_CONTROL_LOC: number,
       public totaL_CONTROL_DOL: number,
       public  usuariO_CREACION: string,
       public  fechA_CREACION: Date,
       public  rowPointer: string,
       public dependencia: string,
       public noteExistsFlag: number,
       public recordDate: Date,
       public  createdBy: string,
       public  updatedBy: string,
       public createDate: Date,
       public documentO_GLOBAL: string
    ) { }
}